require("core.plugin_config.tokyonight")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.alpha")
require("core.plugin_config.lsp_config")
